"""Shared helpers for the verification gates.
bank/*.json   = every question, published or not (legacy_sN = the 170 questions verified by hand + 3 models on 2026-09-29,
                new_sN = generated by scripts/new_sN.py)
verify/state.json = gate results per question id (lint / exec / source / solve / review)
data/questions/sN.json = published = only questions that pass every gate (written by verify/publish.py)
Regenerable caches (fetched pages, solver batches) live in C:/prie-lab/tmp/adsp_verify."""
import glob, json, os, re

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
TMP = 'C:/prie-lab/tmp/adsp_verify'
STATE = os.path.join(ROOT, 'verify', 'state.json')


def load_bank():
    qs = []
    for f in sorted(glob.glob(os.path.join(ROOT, 'bank', '*.json'))):
        for q in json.load(open(f, encoding='utf-8')):
            q['_file'] = os.path.basename(f)
            qs.append(q)
    return qs


def load_state():
    return json.load(open(STATE, encoding='utf-8')) if os.path.exists(STATE) else {}


def save_state(st):
    json.dump(st, open(STATE, 'w', encoding='utf-8'), ensure_ascii=False, indent=1, sort_keys=True)


def norm_text(t):
    t = t.replace('\u00ad', '').replace('\u2212', '-').replace('\u2013', '-').replace('\u2014', '-')
    return re.sub(r'\s+', ' ', t).strip().lower()


def kind(q):
    """exec = answer fixed by running code; concept = answer fixed by a public source; legacy = hand-verified set"""
    if q.get('rcode') or q.get('verify'):
        return 'exec'
    return 'concept'
